"""SFZ rendering via the sfizz_render CLI + VSCO 2 CE sample library.

The premium path for the three instruments with no clean commercially-licensed SF2
(trumpet / strings / bells). sfizz builds cleanly on Linux only, so this renderer is
live on the Modal build and silently unavailable locally on Windows — riff_audio()
falls back to the SF2 registry there. Same fidelity contract as sf_render: notes are
the exact MIDI from sequence.py, looped verbatim across bars.

Pipeline per render: notes -> looped MIDI file (mido) -> sfizz_render -> WAV -> mono
float32 at the engine SR, trimmed/padded to the same frame count sf_render produces.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from ..audio import SR, read_wav, seconds_per_beat

_SFZ_DIR = Path(__file__).resolve().parents[2] / "assets" / "sfz"
_TAIL_S = 0.8  # release/reverb tail, matches sf_render's total-length padding

# instrument -> SFZ path relative to assets/sfz (generated by scripts/fetch_vsco.py).
# Chosen to mirror the app's sampled voices (#42): sustained vibrato articulations.
INSTRUMENT_SFZ: dict[str, str] = {
    "trumpet": "VSCO-2-CE/trumpet/trumpet_susvib.sfz",
    "strings": "VSCO-2-CE/violins/violins_susvib.sfz",
    "bells": "VSCO-2-CE/glock/glock.sfz",
}

# Per-instrument linear gain applied after render (sfizz output is conservative).
_SFZ_GAIN: dict[str, float] = {"trumpet": 1.0, "strings": 1.0, "bells": 1.0}


def sfizz_binary() -> str | None:
    return shutil.which("sfizz_render")


def sfz_path(instrument: str) -> Path | None:
    rel = INSTRUMENT_SFZ.get(instrument)
    if rel is None:
        return None
    p = _SFZ_DIR / rel
    return p if p.exists() else None


def sfz_available(instrument: str) -> bool:
    """True when both the sfizz renderer and this instrument's SFZ are present."""
    return sfizz_binary() is not None and sfz_path(instrument) is not None


def _looped_midi_bytes(notes, tempo: float, bars: int, bar_beats: float) -> bytes:
    """The riff repeated verbatim across `bars` bars, as a type-0 MIDI file."""
    import io

    import mido

    mid = mido.MidiFile(ticks_per_beat=480)
    track = mido.MidiTrack()
    mid.tracks.append(track)
    track.append(mido.MetaMessage("set_tempo", tempo=mido.bpm2tempo(tempo), time=0))

    events: list[tuple[int, int, str, int, int]] = []  # (ticks, order, kind, pitch, vel)
    for b in range(bars):
        bar_off = b * bar_beats
        for n in notes:
            on_t = int(round((bar_off + n.start_beats) * 480))
            off_t = int(round((bar_off + n.start_beats + n.dur_beats) * 480))
            events.append((on_t, 1, "note_on", n.pitch, n.velocity))
            events.append((max(off_t, on_t + 1), 0, "note_off", n.pitch, 0))
    events.sort()

    cur = 0
    for ticks, _, kind, pitch, vel in events:
        track.append(mido.Message(kind, note=pitch, velocity=vel, time=ticks - cur, channel=0))
        cur = ticks
    # push end-of-track out past the release tail so sfizz renders it
    tail_ticks = int(round(_TAIL_S / (seconds_per_beat(tempo)) * 480)) + 480
    track.append(mido.MetaMessage("end_of_track", time=tail_ticks))

    buf = io.BytesIO()
    mid.save(file=buf)
    return buf.getvalue()


def render_riff_sfz(notes, tempo: float, instrument: str, bars: int,
                    bar_beats: float = 4.0, sr: int = SR) -> np.ndarray:
    """Render the exact riff with sfizz + the instrument's SFZ library."""
    sfz = sfz_path(instrument)
    binary = sfizz_binary()
    if sfz is None or binary is None:
        raise RuntimeError(f"sfz renderer unavailable for {instrument!r}")

    total_frames = int((bars * bar_beats * seconds_per_beat(tempo) + _TAIL_S) * sr)

    with tempfile.TemporaryDirectory() as td:
        midi_p = Path(td) / "riff.mid"
        wav_p = Path(td) / "riff.wav"
        midi_p.write_bytes(_looped_midi_bytes(notes, tempo, bars, bar_beats))
        r = subprocess.run(
            [binary, "--sfz", str(sfz), "--midi", str(midi_p), "--wav", str(wav_p),
             "--samplerate", str(sr)],
            capture_output=True, text=True,
        )
        if r.returncode != 0 or not wav_p.exists():
            raise RuntimeError(f"sfizz_render failed for {instrument!r}: {r.stderr[-400:]}")
        audio = read_wav(wav_p, target_sr=sr)

    audio = audio * _SFZ_GAIN.get(instrument, 1.0)
    if len(audio) < total_frames:
        audio = np.pad(audio, (0, total_frames - len(audio)))
    return audio[:total_frames].astype(np.float32)


def library_name(instrument: str) -> str:
    return f"VSCO 2 CE via sfizz ({INSTRUMENT_SFZ.get(instrument, '?')})"
